[env:tsim7000g]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM3
build_flags = 
  -D TINY_GSM_MODEM_SIM7000
  -D MODEM_PWRKEY_PIN=4
  -D MODEM_RX_PIN=26
  -D MODEM_TX_PIN=27
  -D SENSOR_RX_PIN=16
  -D SENSOR_TX_PIN=17
  -D APN_NAME=\"iot.1nce.net\"
  -D UDP_HOST=\"udp.os.1nce.com\"
  -D UDP_PORT=4445
lib_deps =
  vshymanskyy/TinyGSM @ ^0.12.0
  bblanchon/ArduinoJson @ ^6.21.3

