[env:sensor]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags = 
  -D SENSOR_UART_TX=17
  -D SENSOR_UART_RX=16
lib_deps =
  adafruit/Adafruit BME680 Library @ ^2.0.3
  adafruit/Adafruit Unified Sensor @ ^1.1.14

